export type URI =
  | '/promotions/market-access'
  | '/promotions/market'
  | '/promotions/markets'
  | '/promotions/markets/{id}'
  | '/promotions/product'
  | '/promotions/products/images'
  | '/promotions/products/{id}'
  | '/promotions/coupon'
  | '/promotions/coupons/{marketId}'
  | '/benefits/coupons/{marketId}'
